{% set version = "2.3.8" %}

package:
  name: mocsy
  version: {{ version }}

source:
  url: https://github.com/jamesorr/mocsy/archive/v{{ version }}.tar.gz
  sha256: 909540e702ddeb8d2534d96c08910860c68d97dbcd1adfe1976f6e11c6648ab0

build:
  number: 0
  skip: True  # [win or osx or py2k]

requirements:
  build:
    - python
    - setuptools
    - numpy 1.7.*  # [py27]
    - numpy 1.9.*  # [py35]
    - numpy 1.11.*  # [py36]
    - gcc  # [not win]
  run:
    - python
    - numpy >=1.7  # [py27]
    - numpy >=1.9  # [py35]
    - numpy >=1.11  # [py36]
    - libgcc  # [linux]
    - libgfortran  # [osx]

test:
  imports:
    - mocsy
  commands:
    - conda inspect linkages -p $PREFIX mocsy  # [not win]
    - conda inspect objects -p $PREFIX mocsy  # [osx]

about:
  home: https://github.com/jamesorr/mocsy
  license: MIT
  license_file: LICENSE
  summary: 'Routines to model ocean carbonate system thermodynamics.'

extra:
  recipe-maintainers:
    - ocefpaf
