{% set version = "2.4.0" %}

package:
  name: mocsy
  version: {{ version }}

source:
  url: https://github.com/jamesorr/mocsy/archive/v{{ version }}.tar.gz
  sha256: f900ddf1a2845211152124795becb07f550fe2e32a2f6a43374c614070fe068f
  patches:
    - find_fortran.patch

build:
  number: 1001
  skip: True  # [win or osx or py2k]

requirements:
  build:
    - automake  # [not win]
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - python
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - mocsy

about:
  home: https://github.com/jamesorr/mocsy
  license: MIT
  license_file: LICENSE
  summary: 'Routines to model ocean carbonate system thermodynamics'

extra:
  recipe-maintainers:
    - ocefpaf
