{% set version = "2.4.1" %}

package:
  name: mocsy
  version: {{ version }}

source:
  url: https://github.com/jamesorr/mocsy/archive/v{{ version }}.tar.gz
  sha256: f2e08a90eabdd0a30a454f3255352ddf4ffecbc4b3cbb6a1fa6e912f2b90c2a7
  patches:
    - find_fortran.patch

build:
  number: 4
  skip: True  # [win or osx or py2k]

requirements:
  build:
    - automake  # [not win]
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - python
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - mocsy

about:
  home: https://github.com/jamesorr/mocsy
  license: MIT
  license_file: LICENSE
  summary: 'Routines to model ocean carbonate system thermodynamics'

extra:
  recipe-maintainers:
    - ocefpaf
