{% set version = "2.3.7" %}

package:
  name: mocsy
  version: {{ version }}

source:
  url: https://github.com/jamesorr/mocsy/archive/v{{ version }}.tar.gz
  sha256: c454ee617e9cf1b0b8ab2b207a5aae6a5b5bfbc88ec109e390561d73c0b4d08d

build:
  number: 0
  skip: True  # [win or osx or py2k]

requirements:
  build:
    - python
    - setuptools
    - automake  # [not win]
    - numpy 1.7.*  # [py27]
    - numpy 1.9.*  # [py35]
    - numpy 1.11.*  # [py36]
    - gcc  # [not win]
  run:
    - python
    - numpy >=1.7  # [py27]
    - numpy >=1.9  # [py35]
    - numpy >=1.11  # [py36]
    - libgcc  # [linux]
    - libgfortran  # [osx]

test:
  imports:
    - mocsy
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/jamesorr/mocsy
  license: MIT
  license_file: LICENSE
  summary: 'Routines to model ocean carbonate system thermodynamics.'

extra:
  recipe-maintainers:
    - ocefpaf
